In [1]:
from pntk.elements import *
from pntk.petri_net import *
from pntk.example_nets import *
import numpy as np

In [2]:
efm_net = EmptyNet('efm_net')
initial_file_path = 'initial_file/test_net_2.csv'
efm_net.init_by_csv(initial_file_path)

In [3]:
efm_net.print_adj()

identity petri net adjMatrix: 
\	p1	p2	p3	p4	p5	p6	p7	p8	p9	p10	p11	p12	t1	t2	t3	t4	t5	t6	t7	
p1	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	
p2	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	
p3	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	
p4	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	
p5	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	
p6	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	
p7	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	1	1	0	0	
p8	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0	0	1	0	
p9	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	1	
p10	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	
p11	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	
p12	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	
t1	0	1	0	0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	
t2	0	0	1	0	0	0	1	1	0	0	1	0	0	0	0	0	0	0	0	
t3	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	
t4	0	0	0	0	1	0	1	0	1	1	0	1	0	0	0	0	0	0	0	
t5	0	0	0	0	0	1	1	0	1	0	0	0	0	0	0	0	0	0	0	
t6	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	
t7	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	



In [4]:
print(efm_net.get_marking_types())

['0']


In [5]:
print(efm_net.get_place_state())

[[25.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [6]:
print(efm_net.get_transition_state())

[0. 0. 0. 0. 0. 0. 0.]


In [28]:
efm_net.on_fire_transition(efm_net.name_node['t2'])

True

In [8]:
print(efm_net.name_node['t1'].consumption)

3.0


In [9]:
print(efm_net.get_transition_state())

[0. 0. 0. 0. 0. 0. 0.]


In [39]:
efm_net.tick(0.2)
print(efm_net.get_place_state())
print(efm_net.get_transition_state())

[[24.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]]
[0. 0. 0. 0. 0. 0. 0.]
